### ISSUE TITLE
Example app crashes on screen rotation

### ISSUE THREAD

**Issue by MichaelSims** [Zhuinden/realm-monarchy#8]
Reproduced with Pixel XL, Android 8.1.0

Steps to reproduce:

1. Launch the app
2. Rotate the screen
3. App force quits with the following exception:

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/zhuinden/statebundle/StateBundle;
    at com.zhuinden.simplestack.BackstackManager.toBundle(BackstackManager.java:358)
    at com.zhuinden.simplestack.BackstackDelegate.onSaveInstanceState(BackstackDelegate.java:311)
    at com.zhuinden.simplestack.BackstackDelegate$1.onActivitySaveInstanceState(BackstackDelegate.java:220)
    at android.app.Application.dispatchActivitySaveInstanceState(Application.java:243)
    at android.app.Activity.onSaveInstanceState(Activity.java:1577)
    at android.support.v4.app.SupportActivity.onSaveInstanceState(SupportActivity.java:74)
    at android.support.v4.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:526)
    at android.support.v7.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:509)
    at android.app.Activity.performSaveInstanceState(Activity.java:1496)
    at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1386)
    at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:4721)
    at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4672)
    at android.app.ActivityThread.-wrap18(Unknown Source:0)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1595)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6494)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
 Caused by: java.lang.ClassNotFoundException: Didn't find class "com.zhuinden.statebundle.StateBundle" on path: DexPathList[[zip 
file "/data/app/com.zhuinden.monarchyexample-trYtYl9zHvb_E5Y0XhckfA==/base.apk"],nativeLibraryDirectories=[/data/app/com.
zhuinden.monarchyexample-trYtYl9zHvb_E5Y0XhckfA==/lib/arm64, /data/app/com.zhuinden.monarchyexample-
trYtYl9zHvb_E5Y0XhckfA==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    at com.zhuinden.simplestack.BackstackManager.toBundle(BackstackManager.java:358) 
    at com.zhuinden.simplestack.BackstackDelegate.onSaveInstanceState(BackstackDelegate.java:311) 
    at com.zhuinden.simplestack.BackstackDelegate$1.onActivitySaveInstanceState(BackstackDelegate.java:220) 
    at android.app.Application.dispatchActivitySaveInstanceState(Application.java:243) 
    at android.app.Activity.onSaveInstanceState(Activity.java:1577) 
    at android.support.v4.app.SupportActivity.onSaveInstanceState(SupportActivity.java:74) 
    at android.support.v4.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:526) 
    at android.support.v7.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:509) 
    at android.app.Activity.performSaveInstanceState(Activity.java:1496) 
    at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1386) 
    at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:4721) 
    at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4672) 
    at android.app.ActivityThread.-wrap18(Unknown Source:0) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1595) 
    at android.os.Handler.dispatchMessage(Handler.java:106) 
    at android.os.Looper.loop(Looper.java:164) 
    at android.app.ActivityThread.main(ActivityThread.java:6494) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
```
It appears to be an issue with a missing transitive dependency in the `pom.xml` on Jitpack.io for `simple-stack`:

```
<?xml version="1.0" encoding="UTF-8"?>                                
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">            
  <modelVersion>4.0.0</modelVersion>                                  
  <groupId>com.github.Zhuinden</groupId>                              
  <artifactId>simple-stack</artifactId>                               
  <version>1.8.1</version>                                            
  <packaging>aar</packaging>                                          
</project>                                                            
```

Notice the missing dependencies section. Also, the `dependencies` gradle task shows `com.github.Zhuinden:simple-stack:1.8.1` as having no transitive dependencies so `com.github.Zhuinden:state-bundle:1.2.0` is not on the classpath during build time.

**Comment by Zhuinden** [comment]
Gahhhhhhhhh that seems to be caused by https://github.com/dcendents/android-maven-gradle-plugin/issues/61 because it didn't support `api` right

I had a feeling I should update the Jitpack plugin from 1.5 to 2.0... guess I'll release another version with that.

Thank you for reporting!

**Comment by Zhuinden** [comment]
With `simple-stack 1.8.2` this should work now

**Comment by Zhuinden** [comment]
Fixed

**Comment by MichaelSims** [comment]
Thanks!
